### ISSUE TITLE
Clang driver does not accept an `-mOs` option that `newlib` expects mspgcc to accept

### ISSUE THREAD

**Issue by atrosinenko** [access-softek/llvm-project#14]
The `newlib/configure.host` file contains the following line:

```bash
       newlib_cflags="${newlib_cflags} -mOs "
```

This options is not handled by `clang`. With this line commented out, the command line is otherwise accepted by `clang`.

**Comment by asl** [comment]
-mOs is an option ancient mspgcc used to support. Newer msp430-gcc does not support it as well iirc.

**Comment by atrosinenko** [comment]
Testing with TI's mspgcc v. 8.3.1 suggests it accepts `-mOs` (and this seems to be not just due to lack of validation). I have not checked this option really changes the behavior of `gcc` now, though.

```
$ ./msp430-elf-gcc --version
msp430-elf-gcc (ast) 8.3.1
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ./msp430-elf-gcc -c -mOs test.c
$ ./msp430-elf-gcc -c -mOs1 test.c
msp430-elf-gcc: error: unrecognized command line option '-mOs1'; did you mean '-mOs'?
```

**Comment by atrosinenko** [comment]
In access-softek/msp430-clang#11 @chbessonova discovered the following explanation of `-mOs`:
```cpp
     /* This is a hack to work around a problem with the newlib build
     mechanism.  Newlib always appends CFLAGS to the end of the GCC
     command line and always sets -O2 in CFLAGS.  Thus it is not
     possible to build newlib with -Os enabled.  Until now...  */
  if (TARGET_OPT_SPACE && optimize < 3) 
    optimize_size = 1; 
```
In current `msp430-gcc-8.3.1.25` from TI these lines are located in `gcc/config/msp430/msp430.c`.

This could probably be reimplemented in Clang quite easily instead of patching `newlib` and possibly other projects.
