### ISSUE TITLE
[Pauth][lld] Fix unreadable chars issue in `Twine` error message

### ISSUE THREAD

**Issue by kovdan01** [access-softek/llvm-project#50]
For some reason, `Twine` error message obtained via concatenation of string literals and `StringRef`'s (or `std::string`'s - the result was the same) contained unreadable characters, which caused test failure.

The `StringRef`'s containins file names are **not** corrupted: when printing them separately, they are OK, and calling `.str()` on them also gives a correct `std::string` object. Moreover, a `Twine` constructed from a file name only (without concatenation with other stuff) also contains correct string without unreadable characters.

The issue is not related to thread-safety: using a single thread does not resolve it.

The issue is present when both g++ and clang++ are used to compile llvm and lld. The output is a bit different though, but if the issue is related to reading corrupt data from somewhere, different output is what we expect.

**Comment by atrosinenko** [comment]
_Just random thoughts on "Twine" and "unreadable characters"_

Can't this be some kind of UB? From [`Twine`'s documentation](https://llvm.org/doxygen/classllvm_1_1Twine.html#details):

> A Twine is not intended for use directly and should not be stored, its implementation relies on the ability to store pointers to temporary stack objects which may be deallocated at the end of a statement. Twines should only be used accepted as const references in arguments, when an API wishes to accept possibly-concatenated strings.

**Comment by kovdan01** [comment]
Thanks @atrosinenko , I'll check it out! The Twine was originally used there since it was also used in some other similar places - so, if such usage is not permitted, I'll change them all.

**Comment by kovdan01** [comment]
Fix is applied in 315e491c3eb47d23dce6e88ce3354a78ae6d9045
